### PR TITLE
added default toolbar that just has an option to view the list of flags

### PR DESCRIPTION
**Pull request by sarahdagger**
This is for the first issue I have for the week (default toolbar). It does not yet have the feature of changing the menu items when a flag is selected.

### CODE REVIEW

**Review by daphliu-zz — APPROVED** [review]
Looks good to me, nice work!

**Comment by sarahdagger** [comment]
I update the pull request and made the toolbar dynamic so that it shows edit and delete options when a flag is selected, and just the listview option otherwise.

**Comment by sarahdagger** [comment]
Ok really not sure how to fix the conflicts since it's saying that "}" conflicts with "}"...

**Comment by daphliu-zz** [comment]
I think the `}` conflict was because one version had a newline at the end of the file. I fixed it for you so we can merge 😄

**Pull request merged**
